### ISSUE TITLE
Criar um sistema de persistência de Dados.

### ISSUE THREAD

**Issue by diogocezar** [diogocezar/pizzaiolo#10]
Criar um sistema de persistência de dados utilizando SQLite.

**Comment by Jott4** [comment]
Acham que algo assim funciona? @diogocezar @Joao208 

![image](https://user-images.githubusercontent.com/53587274/197651884-67405b95-8ea1-450f-9680-53a37b2ea312.png)

**Comment by Jott4** [comment]
btw o sqlite não suporta enum, então o event_type seria uma string acho

**Comment by diogocezar** [comment]
Então precisamos mesmo de todos esses relacionamentos?

Pq fico pensando, como vamos cadastrar usuários?

E se nós só armazenássemos os PRs?

**Comment by diogocezar** [comment]
Se bem que podemos ir adicionando na medida que as PRs chegam né! É acho que faz sentido sim man!

**Comment by Jott4** [comment]
Isso, acho legal a table de pull Request ter também um status, pra ficar mais fácil na consulta

**Comment by diogocezar** [comment]
Boa! Acho que pode mandar bala lah no PR ;) pq o próximo passo é tirar o in_memory e substituir por esse esquema ai...

**Comment by Joao208** [comment]
Onde vamos salvar a qual mensagem o PR pertence para fazermos atualizações? @Jott4

**Comment by Jott4** [comment]
Bom ponto @Joao208 , talvez adicionamos a table Messages que tem relação 1-1 com Pull Request?

**Comment by diogocezar** [comment]
Pelo que entendi ele usa o timestamp né?

**Comment by Joao208** [comment]
Pois é praticamente isso que a in memory db está fazendo hoje

**Comment by Jott4** [comment]
A Event seria como uma tabela log saca?

Toda vez que o usuário criar, aprovar, recusar uma PR, vai logar na tabela o user_id, a pull_request_id e a ação que o usuário fez

**Comment by Joao208** [comment]
Disponibilizar uma documentação do banco de dados, nomes e o que é cada tabela, o que acha @Jott4?

**Comment by Jott4** [comment]
É uma boa

**Comment by diogocezar** [comment]
Finalizada com a implementação #27
