### ISSUE TITLE
Criar uma Landing Page

### ISSUE THREAD

**Issue by Joao208** [diogocezar/pizzaiolo#17]
@coutinhomm será o designer da Landing Page, @diogocezar @jott4 o que acham de utilizar next como tecnologia, pelo SEO e velocidade de desenvolvimento?

Será mais um site que explica o que é o pizzaiolo, e linka com documentações e builds do git.

**Comment by diogocezar** [comment]
Oxe que massa! Vamos ter uma startup!

**Comment by diogocezar** [comment]
Vale a pena deixar numa pasta separada o site? Outro repo? Outra Branch?

**Comment by Joao208** [comment]
Curto a ideia, já trabalhei com monorepo, e não é mto legal, https://github.com/rafaelandrade/save4me

**Comment by Joao208** [comment]
Logo, acho que faz sentido um repo separado
