### ISSUE TITLE
Verificar o armazenamento dos dados no banco

### ISSUE THREAD

**Issue by diogocezar** [diogocezar/pizzaiolo#33]
Testei aqui com o https://prismaiolo.diocodes.dev/

E os dados parecem estar sendo zerados a cada deploy.

**Comment by Joao208** [comment]
@diogocezar O prisma:push não zera o banco?

Solução gratuita alternativa: 

- https://github.com/planetscale/
- https://planetscale.com/

**Comment by diogocezar** [comment]
Estava pensando aqui, mas acho que por algum motivo não funcionou o gitignore do arquivo do banco, e comitou o local pro de prod!

**Comment by Joao208** [comment]
Mas olhando aqui não está comitado né?

**Comment by diogocezar** [comment]
Agora eu tirei! Mudei o local do banco! Espero que esteja oks, vamos observar na próxima semana com os próximos deploys ;) coloquei em uma pastinha database.

**Comment by diogocezar** [comment]
Aparentemente resolvido.
