### ISSUE TITLE
Comando para reenviar uma mensagem.

### ISSUE THREAD

**Issue by Joao208** [diogocezar/pizzaiolo#41]
![Screenshot 2022-10-29 at 17 49 10](https://user-images.githubusercontent.com/59159025/198851817-6386b3f8-39bc-48e4-b126-ca692d5ada55.png)

Criar um comando para que a pessoa possa reenviar um PR. Ao inves de ter que mandar mensagem e falar "Pessoal, ainda preciso de review aqui."

**Comment by Joao208** [comment]
@diogocezar @Jott4

**Comment by Jott4** [comment]
Seria legal se o autor da pull request reagisse com um emoji especifico na propria mensagem, e então ela fosse reenviada saca?

**Comment by Joao208** [comment]
Genial, talvez um botão igual ao que temos para ver o PR, o que acham?

**Comment by diogocezar** [comment]
Dica do nome do botão:

"Tompero!"
