### ISSUE TITLE
Utilizar a secret que vem dos HOOKs do GH

### ISSUE THREAD

**Issue by diogocezar** [diogocezar/pizzaiolo#9]
Nos hooks enviados pelo GitHub é passado uma secret.

Colocar essa camada de proteção para que só essas requisições conhecidas sejam aceitas.

**Comment by Jott4** [comment]
[related](https://docs.github.com/pt/developers/webhooks-and-events/webhooks/securing-your-webhooks)

**Comment by Joao208** [comment]
É personalizável @diogocezar?

**Comment by diogocezar** [comment]
Sim, podemos inserir qualquer coisa lá.
